# Generated by Django 4.0.3 on 2022-03-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
