# Generated by Django 4.0.3 on 2022-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lesson_course_column_lesson_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(upload_to='course/lesson/video/'),
        ),
    ]
