# Generated by Django 4.0.3 on 2022-03-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='hashed_code',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=225, unique=True)),
            ],
        ),
    ]
